header:
  license:
    spdx-id: GPL-3.0-or-later
    copyright-owner: Print Maker Lab
    content: |
      SPDX-FileCopyrightText: Copyright 2024 Print Maker Lab
      SPDX-License-Identifier: GPL-3.0-or-later
  paths-ignore:
    - '.github/*'
    - '**/*.json'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/schemas'
    - '*.map.js'
    - '*.bundle.js'
    - 'coverage'
    - 'LICENSE'
    - 'yarn.lock'
    - '**/.*'
  comment: always
  language:
    Typescript:
      extensions:
        - ".ts"
        - ".d.ts"
      filenames:
        - "*.ts"
        - "*.d.ts"
      comment_style_id: DoubleSlash