header:
  license:
    spdx-id: GPL-3.0-or-later
    copyright-owner: Print Maker Lab
    content: |
      SPDX-FileCopyrightText: Copyright 2024 Print Maker Lab
      SPDX-License-Identifier: GPL-3.0-or-later
  paths-ignore:
    - '.github/*'
    - '**/*.json'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/schemas'
    - '*.map.js'
    - '*.bundle.js'
    - 'coverage'
    - 'LICENSE'
    - 'yarn.lock'
    - '**/.*'
  comment: always
  # language:
  #   Python:
  #     extensions:
  #       - ".py"
  #     filenames:
  #       - "*.py"
  #     comment_style_id: PythonStyle
  #   Typescript:
  #     extensions:
  #       - ".ts"
  #       - ".d.ts"
  #     filenames:
  #       - "*.ts"
  #       - "*.d.ts"
  #     comment_style_id: DoubleSlash
  #   Html:
  #     extensions:
  #       - ".html"
  #       - ".htm"
  #     filenames:
  #       - "*.html"
  #       - "*.htm"
  #     comment_style_id: AngleBracket
  #   Scss:
  #     extensions:
  #       - ".scss"
  #       - ".css"
  #     filenames:
  #       - "*.scss"
  #       - "*.css"
  #     comment_style_id: Hashtag