header:
  license:
    spdx-id: GPL-3.0-or-later
    copyright-owner: Print Maker Lab
    content: |
      SPDX-FileCopyrightText: Copyright 2024 Print Maker Lab
      SPDX-License-Identifier: GPL-3.0-or-later
  paths-ignore:
    - '.github/*'
    - '**/*.json'
    - '**/*.md'
    - '**/*.yml'
    - '**/*.yaml'
    - '**/build'
    - '**/lib'
    - '**/node_modules'
    - '**/schemas'
    - '*.map.js'
    - '*.bundle.js'
    - 'coverage'
    - 'LICENSE'
    - 'yarn.lock'
    - '**/.*'
  comment: always
  language:
    Python:
      extensions:
        - ".py"
        - ".py3"
      filenames:
        - "*.py"
        - "*.py3"
      comment_style_id: PythonStyle
    Typescript:
      extensions:
        - ".ts"
        - ".d.ts"
      filenames:
        - "*.ts"
        - "*.d.ts"
      comment_style_id: SlashAsterisk
    JavaScript:
      extensions:
        - ".js"
      filenames:
        - "*.js"
      comment_style_id: SlashAsterisk
    HTML:
      extensions:
        - ".html"
        - ".htm"
      filenames:
        - "*.html"
        - "*.htm"
      comment_style_id: AngleBracket
    SCSS:
      extensions:
        - ".scss"
      filenames:
        - "*.scss"
      comment_style_id: DoubleSlash
    CSS:
      extensions:
        - ".css"
      filenames:
        - "*.css"
      comment_style_id: SlashAsterisk