name: Automation Copyright & Licenses

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
  fix-headers:
    if: contains('["Jeredian","Elkin-Vasily","GudwinTheGreat"]', github.actor)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v4

    - name: Generate token
      uses: tibdex/github-app-token@v2.1.0
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Validate License Header        
      uses: apache/skywalking-eyes@v0.5.0
      id: lint_file_headers
      with:
        token: ${{ steps.generate_token.outputs.token }}
        mode: fix
    - name: Apply Changes
      uses: EndBug/add-and-commit@v9.1.4
      env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
      with:
        commit: --signoff
        author_name: Pavel Polyakov
        author_email: djeredian@gmail.com
        message: 'refactor: automatic updating of file headers'