name: Copyright & Licenses

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
  # pull_request_target:

permissions:
    contents: write
    pull-requests: write

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout  
      uses: actions/checkout@v4

    - name: Generate token
      uses: tibdex/github-app-token@v2.1.0
      id: generate_token
      with:
        app_id: ${{ secrets.APP_ID }}
        private_key: ${{ secrets.APP_PRIVATE_KEY }}

    - name: Validate License Header        
      uses: apache/skywalking-eyes@v0.5.0
      id: lint_file_headers
      with:
        token: ${{ steps.generate_token.outputs.token }}
        # og: debug
        # config


    - name: debug
      if: ${{ always() }}
      run: |
        echo "${{ toJson(steps.lint_file_headers)  }}"

    # - uses: marocchino/sticky-pull-request-comment@v2.9.0
    #   # When the previous steps fails, the workflow would stop. By adding this
    #   # condition you can continue the execution with the populated error message.
    #   if: ${{ always() }}
    #   with:
    #     header: ${{ github.job }}
    #     message: |
    #       👋 Hey there
    #       ℹ️ Details:
    #       ```
          
    #       ${{ steps.lint_file_headers.outputs.error_message || 'Everything is OK!' }}

    #       ```
     
    #   # Delete a previous comment when the issue has been resolved
    # - if: ${{ always() && steps.lint_pr_title.outputs.error_message == null }}
    #   uses: marocchino/sticky-pull-request-comment@v2.9.0
    #   with:
    #     header: ${{ github.job }}
    #     delete: true
    #     ignore_empty: false