# SPDX-FileCopyrightText: Copyright 2024 Print Maker Lab
# SPDX-FileCopyrightText: 2022 Free Software Foundation Europe e.V. <https://fsfe.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Copyright & Licenses

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v2
      id: lint_file_headers

    - name: debug
      if: ${{ always() }}
      run: |
        echo "${{ toJson(steps.lint_file_headers.outputs)  }}"

    - uses: marocchino/sticky-pull-request-comment@v2.9.0
      # When the previous steps fails, the workflow would stop. By adding this
      # condition you can continue the execution with the populated error message.
      if: ${{ always() }}
      with:
        header: ${{ github.job }}
        message: |
          👋 Hey there
          ℹ️ Details:
          ```
          ${{ steps.lint_file_headers.outputs.error_message || 'Everything is OK!' }}

          ${{ steps.lint_file_headers.outputs.warning_message || 'Everything is OK!' }}
            ```
     
      # Delete a previous comment when the issue has been resolved
    - if: ${{ always() && steps.lint_pr_title.outputs.error_message == null }}
      uses: marocchino/sticky-pull-request-comment@v2.9.0
      with:
        header: ${{ github.job }}
        delete: true
        ignore_empty: false